import { z } from 'zod'

export const selfServiceIndividualSchema = z.object({
  fullName: z.string().min(1, 'Full name is required'),
  email: z.string().email('Enter a valid email'),
  nationality: z.string().min(1, 'Select nationality'),
  countryOfResidence: z.string().min(1, 'Select country of residence'),
  passportNumber: z.string().min(1, 'Passport number is required'),
  residentStatus: z.string().min(1, 'Select resident status'),
  gender: z.string().min(1, 'Select gender'),
  dateOfBirth: z.string().min(1, 'Date of birth is required'),
  otherNationalities: z.enum(['yes', 'no'], 'Select yes or no'),
  otherNationalityDetails: z.string().optional(),
  nationalIdNumber: z.string().min(1, 'National ID number is required'),
  nationalIdExpiry: z.string().min(1, 'National ID expiry is required'),
  passportExpiry: z.string().min(1, 'Passport expiry is required'),
  externalReferenceNumber: z.string().optional(),
  address: z.string().min(1, 'Address is required'),
  state: z.string().min(1, 'State is required'),
  townCity: z.string().min(1, 'Town / City is required'),
  zipCode: z.string().min(1, 'Zip / Postal code is required'),
  dialingCode: z.string().min(1, 'Dialing code is required'),
  contactNumber: z.string().min(1, 'Contact number is required'),
  workType: z.string().min(1, 'Select work type'),
  industry: z.string().min(1, 'Select industry'),
  productTypeOffered: z.string().min(1, 'Select product type offered'),
  productOffered: z.string().min(1, 'Product offered is required'),
  companyName: z.string().min(1, 'Company name is required'),
  positionsInCompany: z.string().min(1, 'Position in company is required'),
  faceToFaceDeclaration: z.enum(['yes', 'no'], 'Select yes or no'),
  pepCurrentPublicPosition: z.enum(['yes', 'no'], 'Select yes or no'),
  pepHeldPublicPosition12Months: z.enum(['yes', 'no'], 'Select yes or no'),
  pepEverHeldPublicPosition: z.enum(['yes', 'no'], 'Select yes or no'),
  diplomaticImmunity: z.enum(['yes', 'no'], 'Select yes or no'),
  relativeHeldPublicPosition12Months: z.enum(['yes', 'no'], 'Select yes or no'),
  closeAssociateHeldPublicPosition12Months: z.enum(['yes', 'no'], 'Select yes or no'),
  convictionAgainstCourt: z.enum(['yes', 'no'], 'Select yes or no'),
  pepDetails: z.string().optional(),
  sourceOfWealth: z.array(z.string()).min(1, 'Select at least one source of wealth'),
  sourceOfWealthOtherDetails: z.string().optional(),
  sourceOfFunds: z.array(z.string()).min(1, 'Select at least one source of funds'),
  sourceOfFundsOtherDetails: z.string().optional(),
})
